### ISSUE TITLE
SteamDeckGyroDSU not working on deck

### ISSUE THREAD

**Issue by Rahul-Imran** [kmicki/SteamDeckGyroDSU#14]
Whatever app i try the server outputs nothing. I have tried dolphin and yuzu and neither seem to work. Is there any log files i could send to try and understand why? The server is definetely running btw i checked

**Comment by kmicki** [comment]
Try with PadTest from [this site](https://cemuhook.sshnuke.net/padudpserver.html).

In Konsole please execute:

    systemctl --user status sdgyrodsu

when dolphin or yuzu is running and attach output here.

**Comment by Rahul-Imran** [comment]
Ok this is weird af. As soon as i ran padtest it just started working in dolphin. Thanks for taking the time anyway
