### ISSUE TITLE
SDGyroDSU Stopped working

### ISSUE THREAD

**Issue by bpiccolo88** [kmicki/SteamDeckGyroDSU#15]
I've tried uninstalling and restarting the steam deck but it doesn't work in game. I previously had it working but reinstalled cemu and it stopped working ever since. Gyro is working fine otherwise. Attached is the console output when cemu is running.

(deck@steamdeck ~)$ systemctl --user status sdgyrodsu
● sdgyrodsu.service - Steam Deck Gyro DSU Server
     Loaded: loaded (/home/deck/.config/systemd/user/sdgyrodsu.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-05-27 10:10:38 PDT; 19min ago
   Main PID: 11431 (sdgyrodsu)
      Tasks: 4 (limit: 17718)
     Memory: 640.0K
        CPU: 3.569s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/sdgyrodsu.service
             └─11431 /home/deck/sdgyrodsu/sdgyrodsu

May 27 10:30:29 steamdeck sdgyrodsu[11431]: HidDevReader: HID data reading task started.
May 27 10:30:29 steamdeck sdgyrodsu[11431]: HidDevReader: Scan period initial : 3945 us
May 27 10:30:29 steamdeck sdgyrodsu[11431]: HidDevReader: Metronome started.
May 27 10:30:29 steamdeck sdgyrodsu[11431]: CemuhookAdapter: Missed 251 frames.
May 27 10:30:29 steamdeck sdgyrodsu[11431]: Server: Request to subscribe from new client. Dropping current client.
May 27 10:30:29 steamdeck sdgyrodsu[11431]: Server: Initiating frame grab stop.
May 27 10:30:29 steamdeck sdgyrodsu[11431]: CemuhookAdapter: Stopping frame grab.
May 27 10:30:29 steamdeck sdgyrodsu[11431]: HidDevReader: Attempting to stop frame grab...
May 27 10:30:29 steamdeck sdgyrodsu[11431]: HidDevReader: HID data reading task stopped normally.
May 27 10:30:29 steamdeck sdgyrodsu[11431]: HidDevReader: Metronome stopped.

**Comment by kmicki** [comment]
From this short log it looks like there are multiple clients trying to read data. Every time new client tries to read data, the current client is dropped. Please generate longer logfile with command:

    journalctl --user -u sdgyrodsu > sdgyrodsu.log

and attach it here or check if there are multiple messages:

    Server: Request to subscribe from new client. Dropping current client.

Which version of Cemu do you use? Maybe there are multiple instances running fir some reason?

There is handling multiple clients in plans (#13).

**Comment by bpiccolo88** [comment]
@kmicki , attached is the log running the journalctl command. I do see  `Server: Request to subscribe from new client. Dropping current client.` quite a bit. I am using cemu 1.26.2f. I am only running Cemu once, not sure what else would be trying to use the dsu service
[sdgyrodsu (2).log](https://github.com/kmicki/SteamDeckGyroDSU/files/8788905/sdgyrodsu.2.log)
.

**Comment by kmicki** [comment]
It looks like Cemu tries to connect with 2 clients. My guess is you have motion input enabled via cemuhook (Options->Gamepad Motion Source->DSU1->By Slot) and in native Cemu support (Options->Input settings). In Input Settings, try selecting DSU Controller and removing it using - (minus) button.

**Comment by bpiccolo88** [comment]
@kmicki - You were right. I use Emudeck for managing emulators on the deck and it added a DSU controller. I removed it, restarted the deck, and now motion controls are working again. Thanks!!
