### ISSUE TITLE
Instantly crashes

### ISSUE THREAD

**Issue by DerpyBubblez** [kmicki/SteamDeckGyroDSU#21]
(deck@steamdeck sdgyrodsu)$ ./sdgyrodsu 
SteamDeckGyroDSU Vresion: 1.14
Found Steam Deck Controls' HID device at /dev/sub/hiddev0
HidDevReader: Pipeline initilaized. Waiting for start...
CemuhookAdapter: Initialized. Waiting for start of frame grab.
Server: Initializing.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Server: Bind fialed
.Aborted (core udmped)

(Please ignore any spelling errors, copy/pasting does not work properly on my system for some reason, I don't understand how it can possibly paste this badly)

**Comment by kmicki** [comment]
Bind failed means that the UDP port is already used by another process. Most probably you have `sdgyrodsu` installed and it's running in background as a service. You can check it with:

    systemctl --user status sdgyrodsu

**Comment by DerpyBubblez** [comment]
The server does appear to be running, but the only thing that seems to register in Yuzu is a constant down input.

**Comment by kmicki** [comment]
Unfortunately I don't know how it works with yuzu. You can test DSU server with PadTest (

**Comment by DerpyBubblez** [comment]
Pad Test instantly closes, extracted the EXE and both DLLs, tried Wine's flatpak and Proton 7.

**Comment by kmicki** [comment]
I think I had to use GE-Proton for PadTest. Even easier would be if you had a Windows PC in the same network and just run it and input the Deck's IP, Start then select Request Data: 1 on the right.

If you manage to run it on Deck, leave the default address.

**Comment by DerpyBubblez** [comment]
[sdgyrodsu.log](https://github.com/kmicki/SteamDeckGyroDSU/files/9477980/sdgyrodsu.log)
Doesn't seem to output anything useful. I tried ge-proton 7.31 but pad test still crashed. Don't have a Windows system to test unless pad test is 32-bit.

**Comment by DerpyBubblez** [comment]
I'll close this since it's a Yuzu issue at this point.
