### ISSUE TITLE
Windows installer? 

### ISSUE THREAD

**Issue by lsdxm** [kmicki/SteamDeckGyroDSU#28]
Just put Windows on my deck, hoping there's a way to install this on it. Unless Steam-Gyro-For-Cemuhook works?

**Comment by kmicki** [comment]
Code is Linux-specific. It will not work on Windows.

**Comment by lsdxm** [comment]
And there's no plan to make a windows version at all?

**Comment by kmicki** [comment]
No specific plan yet.
