### ISSUE TITLE
Cemu 2.0 Support

### ISSUE THREAD

**Issue by kuhjunge** [kmicki/SteamDeckGyroDSU#36]
Can I use SteamDeckGyroDSU with the Cemu 2.0 Appimage on the Steam Deck?
How should I configure it?

**Comment by kmicki** [comment]
In input Settings you have to add an additional controller (the plus sign near *Controller*) 
![image](https://user-images.githubusercontent.com/1463619/209994956-e1a95ba2-d6b6-48f4-9bd9-e0c7fcac84b6.png)

Then choose DSU Controller and then when it is selected in the list, the only thing you have to set there is tick Motion in the Settings window. Can't make screenshots right now, I'll provide more detailed instructions when I have time.
