### ISSUE TITLE
SteamDeckGyroDSU not working

### ISSUE THREAD

**Issue by tomasdeltell** [kmicki/SteamDeckGyroDSU#4]
Hi!
I've purchased a Steam Deck and want to configure a DSU server on it.
I have another machine where Cemu runs. When I configure the server on Steamdeck Cemu doesn't watch the controller, but service seems running and port is accesible from the Cemu machine, here is a screenshot:
![Screenshot_20220509_140116](https://user-images.githubusercontent.com/8511738/167405793-8cdea2b3-211c-4987-ab74-7838d6feef87.png)
If I start the local service i have on local Cemu machine, it works correctly.
My cemuhook config:
```
[CPU]
affinity = all
customTimerMode = QPC
[Debug]
useH264Decoder = true
mmTimerAccuracy = 1ms
[Input]
motionSource = DSU1
motionSourceIsBtnSource = false
serverIP = 192.168.1.106
serverPort = 26760
```
What could be happening, could you help me?

**Comment by kmicki** [comment]
Hello.

In Cemu in Options -> Gamepad Motion Source does it show MAC address 00:00:00:00:00:00 at DSU1 option?

Please execute `systemctl --user status sdgyrodsu` on Decks' Konsole when Cemu is running and copy output here.

**Comment by tomasdeltell** [comment]
Service is running on Deck.  Cemu shows MAC address 00:00:00:00:00:00 at DSU1 option.
Here is the status of the service:
```
(1)(deck@steamdeck ~)$ systemctl --user status sdgyrodsu.service  -l
● sdgyrodsu.service - Steam Deck Gyro DSU Server
     Loaded: loaded (/home/deck/.config/systemd/user/sdgyrodsu.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-05-09 14:09:34 CEST; 2min 30s ago
   Main PID: 7087 (sdgyrodsu)
      Tasks: 6 (limit: 17718)
     Memory: 576.0K
        CPU: 4.580s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/sdgyrodsu.service
             └─7087 /home/deck/sdgyrodsu/sdgyrodsu

May 09 14:11:03 steamdeck sdgyrodsu[7087]: Cemuhook Server: Initiaiting frame grab start.
May 09 14:11:03 steamdeck sdgyrodsu[7087]: HidDevReader: Attempting to start frame grab.
May 09 14:11:03 steamdeck sdgyrodsu[7087]: HidDevReader: Started frame grab.
May 09 14:11:03 steamdeck sdgyrodsu[7087]: Cemuhook Server: Start sending controller data.
May 09 14:11:03 steamdeck sdgyrodsu[7087]: Scan period initial : 3945 us
May 09 14:11:17 steamdeck sdgyrodsu[7087]: Changed scan period to : 3944 us
May 09 14:11:33 steamdeck sdgyrodsu[7087]: Changed scan period to : 3920 us
May 09 14:11:34 steamdeck sdgyrodsu[7087]: Changed scan period to : 3921 us
May 09 14:11:35 steamdeck sdgyrodsu[7087]: Changed scan period to : 3922 us
May 09 14:11:37 steamdeck sdgyrodsu[7087]: Changed scan period to : 3923 us

```

I noticed that the server port is refusing connections:
```

$ nc -z -v 192.168.1.106 26761
nc: connect to 192.168.1.106 port 26761 (tcp) failed: Connection refused

```

**Comment by kmicki** [comment]
The port is UDP 26760. You're checking TCP 26761.

From the status it all looks good. Seems like Cemu is getting data. How do you test it in Cemu?

 Check following:

- In Cemu in Input Settings, Emulated Controller should be "Wii U GamePad"
- Some games need motion controls to be enabled in game settings (e.g. BOTW)

**Comment by tomasdeltell** [comment]
Sorry, it was a typo, with 20760 port, I have the same result.
In Cemu Settings, I'v tried with "Wii U GamePad" and "Wii U Pro Controller"
Motino Controls are enabled on BoTW (is the game i'm running), it works on my local DSU Server([steam-gyro-for-cemuhook](https://github.com/FrogTheFrog/steam-gyro-for-cemuhook))

**Comment by kmicki** [comment]
When you test from the Deck, do you use also a Steam Controller connected to Steam Deck or you use the Steam Deck itself?

Please also check with this tool: https://files.sshnuke.net/PadTest_1011.zip

**Comment by tomasdeltell** [comment]
I'm testing with the Deck itself. When I configure Cemu to add the Controller i saw this:
![Screenshot_20220509_142506](https://user-images.githubusercontent.com/8511738/167409488-339c42d2-551f-4d61-8e4f-e02d3799cee1.png)

**Comment by kmicki** [comment]
This is built-in Cemu DSU client. It shouldn't be used.

On Cemu side, motion controls should work in the same way as steam-gyro-for-cemuhook for steam controller.

Hard to say what is the problem. If oyu see the zeroed MAC address, that means that Cemu is receiving packets from the Deck. Please test with the PadTest. If you will be able to see a moving controller there, then something's not right on Cemu side.

**Comment by kmicki** [comment]
Sorry for closing, a misclick.

**Comment by tomasdeltell** [comment]
PadTest shows the controller working:
![Screenshot_20220509_151819](https://user-images.githubusercontent.com/8511738/167419095-690a9f0f-893b-4843-89d4-ccc5ef8038ff.png)


But nothing happens on Cemu when i start the game.
What can be wrong at Cemu side? It's working for local Steam controller and for a remote Steam controller on a Raspberry Pi

**Comment by kmicki** [comment]
I really have no idea. Are you sure Steam Controller works through cemuhook and not mapping of gyro to mouse in steam?

Are you testing by aiming with a bow (right trigger)?

**Comment by tomasdeltell** [comment]
I don't know, if idon't start the DSU server on local or RPI the controller doesn't works.

How can I map the controller buttons if i don't can use the Cemu DSU Client?

**Comment by kmicki** [comment]
I use Steam Link to control Cemu on another machine.

This server only handles motion data for now, not other controls.

**Comment by kmicki** [comment]
I will add a remark in README about that. I'm closing the issue.

**Comment by kmicki** [comment]
Added enhancement issue regarding button/axes controls. #6
