### ISSUE TITLE
Cemu crashes when steam deck is offline and SteamDeckGyroDSU is installed

### ISSUE THREAD

**Issue by Askoth** [kmicki/SteamDeckGyroDSU#44]
Hi, today I was trying to play offline and Cemu kept crashing in the steam deck. 

When I turned wifi on, everything was perfect.

when I uninstalled SteamDeckGyroDSU and replaced with a xinput controller that came out of the box in cemu config, it worked perfectly offline as well. 

I don’t inow if it’s possible to fix or if you know about the issue, I’d appreciate if there was a solution for it (even if something I can manually turn off on my side.

Thanks for your time and project :)

**Comment by TomatechGames** [comment]
This is an issue with Cemu itself, rather than SteamDeckGyroDSU. Cemu will crash when offline while the gyro preset is assigned in input settings, even when SteamDeckGyroDSU isn't installed
