### ISSUE TITLE
defferent controllers

### ISSUE THREAD

**Issue by ILyven** [kmicki/SteamDeckGyroDSU#49]
Hello, I've got a steam deck and a pro controller, as I installed the steamdeckgyrodsu,steam deck works perfectly on yuzu while pro controller shows nothing. How can I fix this? Please help me

**Comment by jimliang** [comment]
same

**Comment by pyromancer5** [comment]
i want to use ds5 controller like i do on my pc how can i use enable the gyro for it on cemu? steam deck work fine but not the controller

**Comment by kmicki** [comment]
You'd have to look for other solutions to pass gyro data from other controllers. It's unrelated to this repo.
