### ISSUE TITLE
didn't work

### ISSUE THREAD

**Issue by mrk4869** [kmicki/SteamDeckGyroDSU#54]
for some reason i uninstalled emudeck and reinstall it on a sd card, after that i found steamdeckgyrodsu didn't work.
I tried to uninstall and install steamdeckgyrodsu, but yuzu seems don't accept
(sorry for not a English speaker
[sdgyrodsu.log](https://github.com/kmicki/SteamDeckGyroDSU/files/11770498/sdgyrodsu.log)

**Comment by kmicki** [comment]
Might be the problem described in #45 since latest Steam stable update.

Please try [workaround](https://github.com/kmicki/SteamDeckGyroDSU/issues/45#issuecomment-1511202067).

**Comment by kmicki** [comment]
No response - closing.
