### ISSUE TITLE
Update instructions - workaround for gyro not initializing

### ISSUE THREAD

**Issue by kmicki** [kmicki/SteamDeckGyroDSU#55]
Recent versions of Steam disable provision of gyro values from Steam Deck unless it is configured in a current controller layout to be used.

Provide instructions in readme etc. on how to work around that problem.

The workaround is described [here](https://github.com/kmicki/SteamDeckGyroDSU/issues/45#issuecomment-1511202067).

Related issues: #45 #54

**Comment by Suraevivan** [comment]
I just tap … button under right touch panel on steam deck when I playing Zelda and it works while menu is opened.

**Comment by kmicki** [comment]
Not planned - the issue with gyro not working will be fixed and workaround will not be needed - #64
