### ISSUE TITLE
Completely stuck, CEMU/Yuzu cannot detect server data

### ISSUE THREAD

**Issue by mlc2020** [kmicki/SteamDeckGyroDSU#57]
I'm really struggling with getting this tool to work. I have tried installing manually and through emudeck, rebooting lots, setting gyro to dpad -> cleared from parent for both desktop settings and game specific settings, but I have not been able to get CEMU, Yuzu, or any application to detect server data despite the log (shown below) saying the service had started. Additionally, I checked within steam controller settings to make sure gyro works (which it does). I'm on Stable (SteamOS 3.4.8). Could I verify that this log is correctly initializing and if there is anything I can do for this issue?
```
Aug 10 22:56:22 steamdeck sdgyrodsu[7183]: SteamDeckGyroDSU Version: 1.14
Aug 10 22:56:22 steamdeck sdgyrodsu[7183]: Found Steam Deck Controls' HID device at /dev/usb/hiddev0
Aug 10 22:56:22 steamdeck sdgyrodsu[7183]: HidDevReader: Pipeline initialized. Waiting for start...
Aug 10 22:56:22 steamdeck sdgyrodsu[7183]: CemuhookAdapter: Initialized. Waiting for start of frame grab.
Aug 10 22:56:22 steamdeck sdgyrodsu[7183]: Server: Initializing.
Aug 10 22:56:22 steamdeck sdgyrodsu[7183]: Server: Socket created at IP: 0.0.0.0 Port: 26760.
Aug 10 22:56:22 steamdeck sdgyrodsu[7183]: Server: Initialized.
Aug 10 22:56:22 steamdeck sdgyrodsu[7183]: Server: Start listening for client.
```

**Comment by kmicki** [comment]
Hi. Sorry for the wait. It looks like the server is initialized properly but no application tries to connect. Did you configure Cemu/Yuzu to connect to the server?
