### ISSUE TITLE
Support for BazziteOS - Legion Go

### ISSUE THREAD

**Issue by gt2416** [kmicki/SteamDeckGyroDSU#67]
If installed on Bazzite it doesnt seem to work. 
After a successful install systemctl status sdgyrodsu returns unit not found.
The service file is in the installed location in .config/systemd/user

After manually starting the binary, I still cant get it to work in Yuzu, when testing it says no input data from server.

**Comment by kmicki** [comment]
Do I understand correctly that you're trying to use it on Lenovo Legion Go? This application works exclusively with Steam Deck. It won't work with other devices.

**Comment by gt2416** [comment]
My bad, despite the name I thought it would work on all PC handhelds.
