### ISSUE TITLE
Sudachi Emulator Support

### ISSUE THREAD

**Issue by JaydedCompanion** [kmicki/SteamDeckGyroDSU#68]
Hi! Is Sudachi currently supported? Afaik, Sudachi is a fork of Y*** so I assumed it would be supported out-of-the-box. I've tried manually copying over the gyro config from Y*** and when I press the "Test" button on the config panel it says "Successfully received data from the server", but the gyro controls aren't working (so far I've only tested it in Tears of the Kingdom, but GyroDSU works flawlessly on Y*** with the same save file, etc.) Let me know if I need to provide any further info!

**Comment by ts95** [comment]
I have the same problem with BoTW

**Comment by ts95** [comment]
I got it to work after following this tutorial https://www.youtube.com/watch?v=q-ehLPk9HXI

In game mode while running a Switch game using Sudachi, you need to connect a keyboard and press F11, then open the controller settings. Unless you're using an external monitor with a higher resolution, the "Motion 1" button at the bottom won't be visible at all, so you have to use the tab key to navigate to it and select it, then you press enter to have it listen to gyro data, then you shake the Steam Deck for it to recognize and select the right gyro hook.

<img width="932" alt="image" src="https://github.com/user-attachments/assets/b1257592-405f-476a-ba38-85a35ffbee4d">

**Comment by JaydedCompanion** [comment]
This worked! Thanks for the advice and tutorial link.

To add to @ts95 's solution: you can access the bottom of the config panel without using a keyboard or external monitor by going to the game shortcut's properties (click the little gear icon to the right of the "Play" button, then select "Properties..." from the menu) and under "Shortcut" change "Game Resolution" to something higher than 1080p (I did 2560×1600). This will render the game on a virtually larger screen and thus will shrink the GUI, allowing you to see the "Motion 1" button. If you can't see Sudachi's menu bar after doing this, just click where the menu bar options _would_ be and the dropdown will appear, it just might not render for some reason. 

I also recommend switching the shortcut resolution back to default once you're done, since I assume upscaling will consume even more resources even if Sudachi is running at the native Switch resolution.
