### ISSUE TITLE
Yuzu compatibility

### ISSUE THREAD

**Issue by baggyg** [kmicki/SteamDeckGyroDSU#9]
All working in Cemu -> excellent. Thank you so much! 

The server itself seems to be detected in Yuzu 127.0.0.1 Port 26760. The test shows data is being received. However this never makes it through to the game it seems. Are these the correct settings?

**Comment by KrisCris** [comment]
So how exactly did you solve the issue? I installed everything via emudeck and ran into the same problem, even folks in emudeck discord have no idea.

**Comment by baggyg** [comment]
Which problem? 
The related issue is that by default on steam deck its hard to see the motion button. 
I connected to a monitor to see it:
![steamdeck](https://user-images.githubusercontent.com/4569081/188944638-6aa56581-fa04-4979-97ea-6fc4c20fb2fc.jpg)

https://github.com/yuzu-emu/yuzu/issues/8206
